/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#68dba9",
        "secondary-container": "#fedeb2",
        "secondary-fixed-dim": "#e0c298",
        "on-surface": "#0b1c30",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#005137",
        "inverse-primary": "#bec6e0",
        "secondary": "#725b38",
        "on-secondary-container": "#78603e",
        "on-secondary-fixed-variant": "#584323",
        "surface-container-highest": "#d3e4fe",
        "on-primary-container": "#7c839b",
        "tertiary": "#000000",
        "surface-dim": "#cbdbf5",
        "on-surface-variant": "#45464d",
        "surface-container": "#e5eeff",
        "on-primary": "#ffffff",
        "surface-variant": "#d3e4fe",
        "on-secondary": "#ffffff",
        "surface": "#f8f9ff",
        "surface-container-low": "#eff4ff",
        "primary-container": "#131b2e",
        "on-tertiary-fixed": "#002114",
        "on-error": "#ffffff",
        "primary-fixed": "#dae2fd",
        "primary": "#000000",
        "on-error-container": "#93000a",
        "surface-bright": "#f8f9ff",
        "inverse-on-surface": "#eaf1ff",
        "background": "#f8f9ff",
        "on-tertiary-container": "#069669",
        "secondary-fixed": "#fedeb2",
        "error-container": "#ffdad6",
        "surface-tint": "#565e74",
        "outline": "#76777d",
        "surface-container-high": "#dce9ff",
        "error": "#ba1a1a",
        "on-background": "#0b1c30",
        "primary-fixed-dim": "#bec6e0",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#131b2e",
        "tertiary-container": "#002114",
        "inverse-surface": "#213145",
        "on-secondary-fixed": "#281800",
        "outline-variant": "#c6c6cd",
        "tertiary-fixed": "#85f8c4",
        "on-primary-fixed-variant": "#3f465c",
        // Legacy Brand / Extra Fallbacks
        brand: {
          offwhite: "#fbfbfb",
          navy: "#203145",
          gold: "#b9a077",
          bronze: "#865e37",
          teal: "#447885",
          sky: "#6aafd8",
          royal: "#022cad",
          amber: "#df8714",
        }
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        margin: "2rem",
        gutter: "1.5rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem"
      },
      fontFamily: {
        "label-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "title-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-sm": ["'Playfair Display'", "serif"],
        "headline-lg": ["'Playfair Display'", "serif"],
        "body-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-sm": ["'Playfair Display'", "serif"],
        "body-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-md": ["'Playfair Display'", "serif"],
        "label-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-lg-mobile": ["'Playfair Display'", "serif"],
        "label-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-sm-mobile": ["'Playfair Display'", "serif"],
        "title-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-lg": ["'Playfair Display'", "serif"]
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "title-lg": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "display-sm": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "display-lg-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "700" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "display-sm-mobile": ["28px", { lineHeight: "36px", letterSpacing: "0em", fontWeight: "600" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "display-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "600" }]
      },
      animation: {
        "fade-in": "fadeIn 0.5s ease-out forwards",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0", transform: "translateY(6px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        }
      }
    },
  },
  plugins: [],
}
