/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#000000',
          50: '#f0fdf4',
          100: '#dcfce7',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
        },
        hotel: {
          navy: '#0f172a',
          gold: '#d97706',
          sand: '#f8fafc',
        },
        "surface-container-low": "#f1f3ff",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "outline-variant": "#cfc4c5",
        "on-secondary-fixed-variant": "#404754",
        "outline": "#7e7576",
        "on-tertiary-fixed-variant": "#474747",
        "surface-dim": "#d3daef",
        "on-tertiary-container": "#848484",
        "tertiary-fixed": "#e2e2e2",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "inverse-primary": "#c6c6c6",
        "secondary-fixed": "#dce2f3",
        "on-tertiary-fixed": "#1b1b1b",
        "secondary-container": "#dce2f3",
        "surface-container-high": "#e1e8fd",
        "inverse-on-surface": "#edf0ff",
        "on-secondary-container": "#5e6572",
        "surface-container-highest": "#dce2f7",
        "primary-fixed": "#e2e2e2",
        "surface-variant": "#dce2f7",
        "on-surface-variant": "#4c4546",
        "tertiary-fixed-dim": "#c6c6c6",
        "error": "#ba1a1a",
        "secondary": "#585f6c",
        "on-primary-fixed": "#1b1b1b",
        "on-tertiary": "#ffffff",
        "primary-container": "#1b1b1b",
        "background": "#f9f9ff",
        "on-error-container": "#93000a",
        "surface-tint": "#5e5e5e",
        "error-container": "#ffdad6",
        "on-primary-container": "#848484",
        "surface-container": "#e9edff",
        "tertiary": "#000000",
        "secondary-fixed-dim": "#c0c7d6",
        "surface-bright": "#f9f9ff",
        "on-primary-fixed-variant": "#474747",
        "on-background": "#141b2b",
        "tertiary-container": "#1b1b1b",
        "on-secondary-fixed": "#151c27",
        "surface": "#f9f9ff",
        "primary-fixed-dim": "#c6c6c6",
        "inverse-surface": "#293040",
        "on-surface": "#141b2b"
      },
      spacing: {
        "space-xxs": "2px",
        "space-xs": "4px",
        "space-sm": "8px",
        "space-md": "16px",
        "space-lg": "24px",
        "space-xl": "32px",
        "space-2xl": "48px",
        "space-3xl": "64px",
        "gutter-desktop": "24px",
        "gutter-mobile": "12px",
        "container-max": "1440px"
      },
      fontFamily: {
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "caption": ["Inter", "sans-serif"]
      },
      fontSize: {
        "caption": ["10px", { lineHeight: "12px", letterSpacing: "0.06em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-sm": ["14px", { lineHeight: "20px", letterSpacing: "0.08em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["18px", { lineHeight: "26px", letterSpacing: "0em", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}

